#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
# Yunexal Panel — setup script
# Generates a .env file with a secure random COOKIE_SECRET.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

ENV_FILE=".env"

# Colour helpers
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()    { echo -e "${CYAN}[*]${NC} $*"; }
success() { echo -e "${GREEN}[✓]${NC} $*"; }
warn()    { echo -e "${YELLOW}[!]${NC} $*"; }
error()   { echo -e "${RED}[✗]${NC} $*"; exit 1; }

echo ""
echo -e "${CYAN}╔══════════════════════════════════════╗${NC}"
echo -e "${CYAN}║      Yunexal Panel  v0.1.0           ║${NC}"
echo -e "${CYAN}║      Environment Setup               ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════╝${NC}"
echo ""

# ── Prerequisites ─────────────────────────────────────────────────────────────
info "Checking prerequisites..."
command -v docker  >/dev/null 2>&1 || error "Docker is not installed or not in PATH."
command -v cargo   >/dev/null 2>&1 || error "Rust/Cargo is not installed. Visit https://rustup.rs"
success "Docker and Cargo found."

# ── Existing .env guard ───────────────────────────────────────────────────────
if [[ -f "$ENV_FILE" ]]; then
    warn ".env already exists."
    read -rp "    Overwrite? [y/N] " answer
    [[ "${answer,,}" == "y" ]] || { info "Aborted. Existing .env kept."; exit 0; }
fi

# ── Interactive prompts ───────────────────────────────────────────────────────
echo ""
info "Configure admin credentials"

read -rp "  Admin username [admin]: " PANEL_USERNAME
PANEL_USERNAME="${PANEL_USERNAME:-admin}"

while true; do
    read -rsp "  Admin password: " PANEL_PASSWORD; echo
    [[ ${#PANEL_PASSWORD} -ge 8 ]] && break
    warn "Password must be at least 8 characters."
done

read -rsp "  Confirm password: " PANEL_PASSWORD_CONFIRM; echo
[[ "$PANEL_PASSWORD" == "$PANEL_PASSWORD_CONFIRM" ]] || error "Passwords do not match."

# ── Generate COOKIE_SECRET (64 random bytes → hex = 128 chars) ───────────────
info "Generating secure COOKIE_SECRET (64 bytes)..."

if command -v openssl >/dev/null 2>&1; then
    COOKIE_SECRET=$(openssl rand -hex 64)
elif [[ -r /dev/urandom ]]; then
    COOKIE_SECRET=$(LC_ALL=C tr -dc 'a-f0-9' < /dev/urandom | head -c 128)
else
    error "Cannot generate a secure secret: openssl and /dev/urandom both unavailable."
fi

[[ ${#COOKIE_SECRET} -eq 128 ]] || error "COOKIE_SECRET length unexpected: ${#COOKIE_SECRET} chars (expected 128)."
success "COOKIE_SECRET generated."

# ── Write .env ────────────────────────────────────────────────────────────────
cat > "$ENV_FILE" <<EOF
# Yunexal Panel — Environment Configuration
# Generated by setup.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# ─────────────────────────────────────────────────────────────

# Admin credentials (applied on every startup)
PANEL_USERNAME=${PANEL_USERNAME}
PANEL_PASSWORD=${PANEL_PASSWORD}

# 128-char hex string (64 random bytes) used to sign/encrypt session cookies.
# Changing this value will invalidate all active sessions.
COOKIE_SECRET=${COOKIE_SECRET}
EOF

chmod 600 "$ENV_FILE"
success ".env written and permissions set to 600."

# ── Pull Alpine image (used for volume operations) ────────────────────────────
if ! docker image inspect alpine:latest >/dev/null 2>&1; then
    info "Pulling alpine:latest (required for volume file operations)..."
    docker pull alpine:latest
    success "alpine:latest pulled."
else
    success "alpine:latest already present."
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}Setup complete!${NC}"
echo ""
echo "  Build and run:"
echo -e "    ${CYAN}cargo run${NC}"
echo ""
echo "  Open in browser:"
echo -e "    ${CYAN}http://localhost:3000${NC}"
echo ""
